# Generated by Django 5.0.3 on 2024-04-02 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0003_alter_rate_ratevalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="FeaturedProjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Project.project",
                    ),
                ),
            ],
        ),
    ]
