# Generated by Django 5.0.3 on 2024-03-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_remove_project_tags_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
