# Generated by Django 5.0.3 on 2024-03-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customform',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customform',
            name='facebook_profile',
            field=models.URLField(null=True),
        ),
    ]
